### ISSUE TITLE
how to query multiple variants at once time in FORGEdb?

### ISSUE THREAD

**Issue by Y-Isaac** [charlesbreeze/FORGEdb#1]
Hi, 

Thanks for your effort in construct it, in my mind it integrated more useful database than earlier tool, I want to use it. But I don't know how to query several variants at once time since the risk variants in my study is thousands. I saw an API page on the official website, but I'm not sure how to achieve my goal. Can you provide more detailed help? Thanks for your help in advance!

**Comment by charlesbreeze** [comment]
Hi Isaac,

Here is a walk-through the API, with 1, 2 and 3 corresponding to the 3 sections we see at https://forgedb.cancer.gov/api-access/:

1. The first section shows what types of data are available (e.g. gtex, closest gene, etc.). If you select the first section, press "try it out" and then select "execute" you will get the following line of code:

```
curl -X 'GET' \
  'https://forgedb.cancer.gov/api/datasets.json' \
  -H 'accept: */*'
```

This is a line of code that can be copy pasted into a mac/linux terminal, and will download all the types of data/datasets that are available and show them on the screen.

2. The second section shows how each dataset is structured (column headers). If you select the second section, press "try it out" and then select "execute" you will get the following line of code:

```
curl -X 'GET' \
  'https://forgedb.cancer.gov/api/closest_gene/v1.0/schema.json' \
  -H 'accept: */*'
```

Note that the dataset we look at here (in this case closest gene) is one of the datasets listed in step 1. We can select other datasets to see the column headers (e.g. gtex).

3. The third section shows us how to get data for individual variants and datasets. For example, to get information on rs12203592 and closest gene:

```
curl -X 'GET' \
  'https://forgedb.cancer.gov/api/closest_gene/v1.0/rs12203592.json' \
  -H 'accept: */*'
```

All of these commands can print to files by using " > filename" at the end of the command, and a script in e.g. bash or python (wrapping around these curl commands) can be used to scale this up to thousands of variants. 

If you are interested in FORGEdb scores (these scores aggregate all datasets), these are available through LDlinkR and https://zenodo.org/records/8293408, as well as LDassoc (https://ldlink.nih.gov/?tab=ldassoc), LDproxy (https://ldlink.nih.gov/?tab=ldproxy) and LDmatrix (https://ldlink.nih.gov/?tab=ldmatrix). 

If you prefer to work with FORGEdb tables, they are available at https://zenodo.org/records/10067458. Using grep and the rsid of each variant against the tables can also be a way to query FORGEdb data, but the API is likely to be faster and more structured. 

Let me know if you have any more questions!

C

**Comment by Y-Isaac** [comment]
Thanks! I get it! But I have another question that I would like to ask you: Some variants cannot be annotated to the rsid yet, so are these variants cannot be queried in FORGEdb(most of them are INDEL)?

**Comment by charlesbreeze** [comment]
Hi Isaac,

FORGEdb is expanding, going from 37 million variants to 59 million (current version), and we are going to expand FORGEdb further.

If you don't find some variants annotated, they will likely be annotated in the future. We have made an effort to include a large amount of common variants though.

Let me know if you have any more questions!

C

**Comment by Y-Isaac** [comment]
> Hi Isaac,
> 
> FORGEdb is expanding, going from 37 million variants to 59 million (current version), and we are going to expand FORGEdb further.
> 
> If you don't find some variants annotated, they will likely be annotated in the future. We have made an effort to include a large amount of common variants though.
> 
> Let me know if you have any more questions!
> 
> C

Thanks, I have no more question. Expressing my gratitude and respect to you once again!
