### ISSUE TITLE
How to further query the TF Motif information involved in the FORGEdb results?

### ISSUE THREAD

**Issue by Y-Isaac** [charlesbreeze/FORGEdb#2]
HI,

Thanks for this tools. I would like to inquire about how to further understand the TF Motif information related to the SNP I submitted. For example, I submitted the SNP rs10409243, the result shows that it belong to TF Motif _V_AP4_Q6_, but I don't understand what it actually represents, and the TF Motif _V_AP4_Q6_ is not a standard name. I also try to query it in url _https://eforge-tf.altiusinstitute.org/_, but there doesn't seem to have the information I'm looking for either.

May be my quetion is a little silly, I am new in this field. Thanks for your help in advanced!

Best regards,
Issac

**Comment by charlesbreeze** [comment]
Hi Isaac,

Motifs from [FORGE2-TF](https://forge2-tf.altiusinstitute.org/) and [eFORGE-TF](https://eforge-tf.altiusinstitute.org/) come from several main sources: a) TRANSFAC, b) JASPAR, c) UniPROBE, and d) the TF motifs obtained from Jussi Taipale’s lab -which are coded “Taipale”. These admittedly are a range of sources, have you tried searching for the TF motif "V_AP4_Q6" in google/pubmed? For some motifs we have to go back to these sources, for others there are multiple annotations present online, available via google/pubmed.

A google search for "V_AP4_Q6" brings up more details for this TRANSFAC motif for the gene transcription factor AP-4 (activating enhancer binding protein 4):

- text with details: https://www2.stat.duke.edu/~sayan/assess/genesets/Jan2006/cards/C3/V_AP4_Q6.shtml

- TF motif logos for AP-4 motifs, among others: http://www.mauranolab.org/CATO/weblogos/DataS2.pdf

- consensus sequence: https://www.bioinformatics.org/grn/matrix_list

Given the many sources, it is admittedly not always easy to pinpoint data in every single case, but searching in these repositories should cover most motifs.

Let me know if you have any more questions!

Best,

Charles

**Comment by Y-Isaac** [comment]
I have learned a lot and I really appreciate your meticulous answers!
